<a href="https://colab.research.google.com/github/priyankareddii/FML1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **0-Dimension array**

**1**

In [ ]:
a=np.array(200)
print(a)

200


**2**

In [ ]:
a=np.array(40)
print(a)

40


**3**

In [ ]:
a=np.array(450)
print(a)

450


**4**

In [ ]:
a=np.array(560)
print(a)

560


# **1-Dimension array**


# Collection of 0 elements is form 1-dimension

**1**

In [ ]:
a=np.array([200,300,400,500])
print(a)

[200 300 400 500]


**2**

In [ ]:
a=np.array([40,50,60,70])
print(a)

[40 50 60 70]


**3**

In [ ]:
a=np.array([500,600,700,800])
print(a)

[500 600 700 800]


**4**

In [ ]:
a=np.array([150,170,180,190])
print(a)

[150 170 180 190]


# **2-Dimension array**

# 0 th sublist

# 1st sublist

**1**

In [ ]:
a=np.array([[200,300],[400,500]])
print(a)

[[200 300]
 [400 500]]


In [ ]:
a[1][0]

400

In [ ]:
a[0][1]

300

**2**

In [ ]:
a=np.array([[600,650],[700,750]])
print(a)

[[600 650]
 [700 750]]


**3**

In [ ]:
a=np.array([[150,160],[170,180]])
print(a)

[[150 160]
 [170 180]]


**4**

In [ ]:
a=np.array([[40,50],[45,55]])
print(a)

[[40 50]
 [45 55]]


In [ ]:
a[0][0]

40

# **3-Dimension array**

# collection of 2-dimensions

**1**

In [ ]:
a=np.array([[[200,300],[400,500]],[[600,700],[800,900]]])
print(a)

[[[200 300]
  [400 500]]

 [[600 700]
  [800 900]]]


In [ ]:
a[0][1][0]

400

**2**

In [ ]:
a=np.array([[[140,150],[120,130]],[[110,115],[160,170]]])
print(a)

[[[140 150]
  [120 130]]

 [[110 115]
  [160 170]]]


**3**

In [ ]:
a=np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(a)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


**4**

In [ ]:
a=np.array([[[111,222],[333,444]],[[555,666],[777,888]]])
print(a)

[[[111 222]
  [333 444]]

 [[555 666]
  [777 888]]]


In [ ]:
a[0][0][0]

111

In [ ]:
a[0][1][1]

444

# **asarray()**

**1**

In [ ]:
a=[200,300,400,500]
b=np.array(a,dtype=float)
print(b)

[200. 300. 400. 500.]


**row major order("C")**

**column major order("F")**

**occured in 2-dimension**

In [ ]:
a=[[200,300],[400,500]]
b=np.asarray(a,order="C")
print(b)

[[200 300]
 [400 500]]


In [ ]:
for i in np.nditer(b):
  print(i)

200
300
400
500


In [ ]:
a=[[200,300],[400,500]]
b=np.asarray(a,order="F")
print(b)

[[200 300]
 [400 500]]


In [ ]:
for i in np.nditer(b):
  print(i)

200
400
300
500


**2**

In [ ]:
a=[250,350,450,550]
b=np.asarray(a,dtype=float)
print(b)

[250. 350. 450. 550.]


In [ ]:
a=[[250,350],[450,550]]
b=np.asarray(a,order="C")
print(b)

[[250 350]
 [450 550]]


In [ ]:
for i in np.nditer(b):
  print(i)

250
350
450
550


In [ ]:
a=[[250,350],[450,550]]
b=np.asarray(a,order="F")
print(b)

[[250 350]
 [450 550]]


In [ ]:
for i in np.nditer(b):
  print(i)

250
450
350
550


**3**

In [ ]:
a=[14,15,16,17]
b=np.asarray(a,dtype=float)
print(b)

[14. 15. 16. 17.]


In [ ]:
a=[[14,15],[16,17]]
b=np.asarray(a,order="C")
print(b)

[[14 15]
 [16 17]]


In [ ]:
for i in np.nditer(b):
  print(i)

14
15
16
17


In [ ]:
a=[[14,15],[16,17]]
b=np.asarray(a,order="F")
print(b)

[[14 15]
 [16 17]]


In [ ]:
for i in np.nditer(b):
  print(i)

14
16
15
17


**4**

In [ ]:
a=[111,222,333,444]
b=np.asarray(a,dtype=float)
print(b)

[111. 222. 333. 444.]


In [ ]:
a=[[111,222],[333,444]]
b=np.asarray(a,order="C")
print(b)

[[111 222]
 [333 444]]


In [ ]:
for i in np.nditer(b):
  print(i)

111
222
333
444


In [ ]:
a=[[111,222],[333,444]]
b=np.asarray(a,order="F")
print(b)

[[111 222]
 [333 444]]


In [ ]:
for i in np.nditer(b):
  print(i)

111
333
222
444


# **frombuffer()**

### **converts the string into buffer**

## **using b before the string**

**1**

In [ ]:
a=b"First Year CSE Students"
np.frombuffer(a,dtype="S1")

array([b'F', b'i', b'r', b's', b't', b' ', b'Y', b'e', b'a', b'r', b' ',
       b'C', b'S', b'E', b' ', b'S', b't', b'u', b'd', b'e', b'n', b't',
       b's'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=15)

array([b'F', b'i', b'r', b's', b't', b' ', b'Y', b'e', b'a', b'r', b' ',
       b'C', b'S', b'E', b' '], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",offset=12)

array([b'S', b'E', b' ', b'S', b't', b'u', b'd', b'e', b'n', b't', b's'],
      dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=3,offset=15)

array([b'S', b't', b'u'], dtype='|S1')

**2**

In [ ]:
a=b"Second Year CSE  Boys"
np.frombuffer(a,dtype="S1")

array([b'S', b'e', b'c', b'o', b'n', b'd', b' ', b'Y', b'e', b'a', b'r',
       b' ', b'I', b'T', b' ', b'B', b'o', b'y', b's'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=12)

array([b'S', b'e', b'c', b'o', b'n', b'd', b' ', b'Y', b'e', b'a', b'r',
       b' '], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",offset=15)

array([b'B', b'o', b'y', b's'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=4,offset=12)

array([b'I', b'T', b' ', b'B'], dtype='|S1')

**3**

In [ ]:
a=b"First Year all Boys"
np.frombuffer(a,dtype="S1")

array([b'F', b'i', b'r', b's', b't', b' ', b'Y', b'e', b'a', b'r', b' ',
       b'a', b'l', b'l', b' ', b'B', b'o', b'y', b's'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=6)

array([b'F', b'i', b'r', b's', b't', b' '], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",offset=8)

array([b'a', b'r', b' ', b'a', b'l', b'l', b' ', b'B', b'o', b'y', b's'],
      dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=2,offset=9)

array([b'r', b' '], dtype='|S1')

**4**

In [ ]:
a=b"Python is very useful Language"
np.frombuffer(a,dtype="S1")

array([b'P', b'y', b't', b'h', b'o', b'n', b' ', b'i', b's', b' ', b'v',
       b'e', b'r', b'y', b' ', b'u', b's', b'e', b'f', b'u', b'l', b' ',
       b'L', b'a', b'n', b'g', b'u', b'a', b'g', b'e'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=6)

array([b'P', b'y', b't', b'h', b'o', b'n'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",offset=6)

array([b' ', b'i', b's', b' ', b'v', b'e', b'r', b'y', b' ', b'u', b's',
       b'e', b'f', b'u', b'l', b' ', b'L', b'a', b'n', b'g', b'u', b'a',
       b'g', b'e'], dtype='|S1')

In [ ]:
np.frombuffer(a,dtype="S1",count=3,offset=8)

array([b's', b' ', b'v'], dtype='|S1')

# **fromiter()**

**1**

In [ ]:
a=[200,300,400,500,600,700]
np.fromiter(a,dtype=int,count=3)

array([200, 300, 400])

In [ ]:
np.fromiter(a,dtype=float,count=3)

array([200., 300., 400.])

In [ ]:
np.fromiter(a,dtype="S1",count=3)

array([b'2', b'3', b'4'], dtype='|S1')

**2**

In [ ]:
a=[150,250,350,450,550,650,750]
np.fromiter(a,dtype=int,count=3)

array([150, 250, 350])

In [ ]:
np.fromiter(a,dtype=float,count=3)

array([150., 250., 350.])

In [ ]:
np.fromiter(a,dtype="S1",count=3)

array([b'1', b'2', b'3'], dtype='|S1')

**3**

In [ ]:
a=[111,222,333,444,555,666,777]
np.fromiter(a,dtype=int,count=5)

array([111, 222, 333, 444, 555])

In [ ]:
np.fromiter(a,dtype=float,count=5)

array([111., 222., 333., 444., 555.])

In [ ]:
np.fromiter(a,dtype="S1",count=5)

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

**4**

In [ ]:
a=[121,213,324,435,546,657,768]
np.fromiter(a,dtype=int,count=4)

array([121, 213, 324, 435])

In [ ]:
np.fromiter(a,dtype=float,count=4)

array([121., 213., 324., 435.])

In [ ]:
np.fromiter(a,dtype="S1",count=4)

array([b'1', b'2', b'3', b'4'], dtype='|S1')

# **INITIALIZING ARRAYS**

After creating arrays,assigning some values.

# **zeros()**

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a=np.zeros([5,4],dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
a=np.zeros([5,4,4])
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# **full()**

In [ ]:
a=np.full([4,6],4)
print(a)

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [ ]:
a=np.full([4,4,4],6)
print(a)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


# **random.rand()**

## Output in between 0 to 1
## No use of subscript

In [ ]:
a=np.random.rand(5,6)
print(a)

[[1.17196091e-01 4.05087737e-01 7.78700476e-01 4.50814682e-01
  2.90696738e-01 6.92612173e-04]
 [4.37715956e-02 8.50469370e-01 8.55021689e-02 3.00383819e-01
  1.60425619e-01 3.80948714e-01]
 [4.05011289e-02 7.52725581e-01 5.89051804e-02 7.78681875e-01
  2.37883703e-01 8.55322923e-01]
 [3.18891924e-01 3.72320952e-01 4.70199479e-02 1.62793111e-01
  1.46502926e-01 1.74754921e-02]
 [2.60084560e-01 2.26034680e-01 1.81578139e-01 1.58362704e-01
  9.97973639e-01 6.43585053e-01]]


In [ ]:
a=np.random.rand(4,4,4)
print(a)

[[[0.13833117 0.81157459 0.46436453 0.4550295 ]
  [0.32042112 0.77560127 0.52308137 0.65949661]
  [0.10624679 0.309335   0.98724595 0.36076458]
  [0.34174897 0.25235603 0.4727578  0.81133112]]

 [[0.41115821 0.64287696 0.39255657 0.83470662]
  [0.79476067 0.94673395 0.90937976 0.26370304]
  [0.61182367 0.49143112 0.70971378 0.54260502]
  [0.42997509 0.49227636 0.88675409 0.14754089]]

 [[0.31846695 0.32440488 0.33494427 0.07576896]
  [0.65719106 0.96646484 0.10534891 0.38800339]
  [0.08813395 0.41222214 0.97429089 0.49215764]
  [0.87175453 0.45479454 0.12568485 0.61084855]]

 [[0.66138143 0.45328    0.55690628 0.00164041]
  [0.39386026 0.88985567 0.51217297 0.52886947]
  [0.80573906 0.49410188 0.22914956 0.22226805]
  [0.91670173 0.93624879 0.44399008 0.25194074]]]


# **ones()**

In [ ]:
a=np.ones([4,6],dtype=int)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
a=np.ones([4,4,6],dtype=int)
print(a)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


# **eye**

diagonal elements are 1 remaining are 0  
2/2 matrix or 4/4 matrix

In [ ]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a=np.eye(8)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


# **NUMERICAL RANGE**

* arange()
* reshape()
* linspace()
* logspace()



### values are printed between the given range  
### start stop step (difference)

# **arange()**

In [ ]:
a=np.arange(30,50,2)
print(a)

[30 32 34 36 38 40 42 44 46 48]


In [ ]:
a=np.arange(0,105,5,dtype=float)
print(a)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


In [ ]:
a=np.arange(100,1000,100)
print(a)

[100 200 300 400 500 600 700 800 900]


In [ ]:
a=np.arange(30,50,2)
print(a)

[30 32 34 36 38 40 42 44 46 48]


# **reshape()**

### equal division matrix

In [ ]:
a.reshape(5,2)

array([[30, 32],
       [34, 36],
       [38, 40],
       [42, 44],
       [46, 48]])

In [ ]:
a.reshape(2,5)

array([[30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [ ]:
a.reshape(1,10)

array([[30, 32, 34, 36, 38, 40, 42, 44, 46, 48]])

In [ ]:
a.reshape(10,1)

array([[30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48]])

# **linspace()**

### last element also considered

In [ ]:
a=np.linspace(0,100,20,endpoint=False,retstep=True,dtype=int)
# equal intervals 20
# difference retstep
# False means endpoint not considered
print(a)

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95]), 5.0)


In [ ]:
a=np.linspace(10,100,10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
a=np.linspace(10,100,10,endpoint=False) # equal intervals 10
print(a)

[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [ ]:
a=np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)     #  equal intervals 10  # difference retstep
print(a)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)


# **logspace()**

### logarithemic values

In [ ]:
a=np.logspace(1,10,10,base=2,dtype=int)
print(a)

[   2    4    8   16   32   64  128  256  512 1024]


In [ ]:
a=np.logspace(1,10,10,dtype=int)
print(a)

[         10         100        1000       10000      100000     1000000
    10000000   100000000  1000000000 10000000000]


# **ARRAY PROPERTIES**

### SIZE - np.size(array)
### SHAPE - np.shape(array)
### DTYPE - a.dtype

In [ ]:
a=np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a=a.reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.size(a)

9

In [ ]:
np.shape(a)

(3, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.array([10,20,30],dtype=float)
print(b)

[10. 20. 30.]


In [ ]:
b.dtype

dtype('float64')

# **ARRAY OPERATIONS**

* ### Accessing the elements
* ### Slicing - Means extracting some portion of data  

### Accessing and slicing Operations
concatenate()

copy()

stack()

view

vstack()

sort()

dstack()

reshape()

hstack()

append()

split()

insert()

where()

delete()

searchsorted()

### **Accessing and Slicing Operations**

In [ ]:
a=np.array([[234,387,465,834,964,201],[543,500,823,645,823,923]])
print(a)

[[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
a[0]

array([234, 387, 465, 834, 964, 201])

In [ ]:
a[1]

array([543, 500, 823, 645, 823, 923])

In [ ]:
a[1][1]

500

In [ ]:
a[1][4]

823

In [ ]:
h=np.arange(10,200,10)
print(h)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190]


In [ ]:
h[5:16] # excluded 16th element

array([ 60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160])

In [ ]:
h=np.arange(10,3000,10)
print(h)

[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000 1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
 1130 1140 1150 1160 1170 1180 1190 1200 1210 1220 1230 1240 1250 1260
 1270 1280 1290 1300 1310 1320 1330 1340 1350 1360 1370 1380 1390 1400
 1410 1420 1430 1440 1450 1460 1470 1480 1490 1500 1510 1520 1530 1540
 1550 1560 1570 1580 1590 1600 1610 1620 1630 1640 1650 1660 1670 1680
 1690 1700 1710 1720 1730 1740 1750 1760 1770 1780 1790 1800 1810 1820
 1830 1840 1850 1860 1870 1880 1890 1900 1910 1920 1930 1940 1950 1960
 1970 

In [ ]:
h[123:212]

array([1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340,
       1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450,
       1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540, 1550, 1560,
       1570, 1580, 1590, 1600, 1610, 1620, 1630, 1640, 1650, 1660, 1670,
       1680, 1690, 1700, 1710, 1720, 1730, 1740, 1750, 1760, 1770, 1780,
       1790, 1800, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890,
       1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000,
       2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100, 2110,
       2120])

# **copy()**

### copying one array elements into another array

In [ ]:
a=np.array([[234,387,465,834,964,201],[543,500,823,645,823,923]])
print(a)

[[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
b=np.array([[364,296,975,345,253,785],[241,940,823,764,241,623]])
print(b)

[[364 296 975 345 253 785]
 [241 940 823 764 241 623]]


In [ ]:
b=np.copy(a)
print(b)

[[234 387 465 834 964 201]
 [543 500 823 645 823 923]]


In [ ]:
a,b

(array([[234, 387, 465, 834, 964, 201],
        [543, 500, 823, 645, 823, 923]]),
 array([[234, 387, 465, 834, 964, 201],
        [543, 500, 823, 645, 823, 923]]))

In [ ]:
b=np.array([[364,296,975,345,253,785],[241,940,823,764,241,623]])
print(b)

[[364 296 975 345 253 785]
 [241 940 823 764 241 623]]


In [ ]:
a=np.copy(b)
print(a)

[[364 296 975 345 253 785]
 [241 940 823 764 241 623]]


In [ ]:
a,b

(array([[364, 296, 975, 345, 253, 785],
        [241, 940, 823, 764, 241, 623]]),
 array([[364, 296, 975, 345, 253, 785],
        [241, 940, 823, 764, 241, 623]]))

# **view**

### similar to copy but its acts like a reference

In [ ]:
c=b.view()
c

array([[364, 296, 975, 345, 253, 785],
       [241, 940, 823, 764, 241, 623]])

In [ ]:
print("a=",a)
print("b=",b)
print("c=",c)

a= [[364 296 975 345 253 785]
 [241 940 823 764 241 623]]
b= [[364 296 975 345 253 785]
 [241 940 823 764 241 623]]
c= [[364 296 975 345 253 785]
 [241 940 823 764 241 623]]


In [ ]:
a[1][2]=777
a

array([[364, 296, 975, 345, 253, 785],
       [241, 940, 777, 764, 241, 623]])

In [ ]:
b

array([[364, 296, 975, 345, 253, 785],
       [241, 940, 823, 764, 241, 623]])

In [ ]:
c

array([[364, 296, 975, 345, 253, 785],
       [241, 940, 823, 764, 241, 623]])

In [ ]:
b[0][4]=999
b

array([[364, 296, 975, 345, 999, 785],
       [241, 940, 823, 764, 241, 623]])

# **sort()**

### sorting the elements

In [ ]:
a=np.array([4325,3548,1911,8912,9012,3219,4358,8230])
print(a)

[4325 3548 1911 8912 9012 3219 4358 8230]


In [ ]:
np.sort(a)

array([1911, 3219, 3548, 4325, 4358, 8230, 8912, 9012])

In [ ]:
a=a.reshape(2,4)
print(a)

[[4325 3548 1911 8912]
 [9012 3219 4358 8230]]


In [ ]:
a=a.reshape(8,1)
print(a)

[[4325]
 [3548]
 [1911]
 [8912]
 [9012]
 [3219]
 [4358]
 [8230]]


BASED ON AXIS MAXIMUM FUNCTIONS ARE

# AXIS:0 MEANS COLUMN WISE OPERATIONS
# **AXIS:1 MEANS ROW WISE OPERATIONS**

In [ ]:
a=np.array([[234,687,465,834.964,909],[543,500,823,645,823,723]])
print(a)

[list([234, 687, 465, 834.964, 909]) list([543, 500, 823, 645, 823, 723])]


<ipython-input-131-0ad2d7daf99f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[234,687,465,834.964,909],[543,500,823,645,823,723]])


In [ ]:
np.sort(a,axis=0)

array([list([234, 687, 465, 834.964, 909]),
       list([543, 500, 823, 645, 823, 723])], dtype=object)

# reshape()

In [ ]:
a=np.array([22,33,44,55,66,77])
a

array([22, 33, 44, 55, 66, 77])

In [ ]:
a.reshape(2,3)

array([[22, 33, 44],
       [55, 66, 77]])

In [ ]:
a=np.arange(2,33,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

**append()**

append is applied between two arrays

In [ ]:
a=np.array([20,30,40,50,60])
print(a)

[20 30 40 50 60]


In [ ]:
b=np.array([22,32,42,52,62])
print(a)

[20 30 40 50 60]


In [ ]:
np.append(a,b)

array([20, 30, 40, 50, 60, 22, 32, 42, 52, 62])

In [ ]:
np.append(a,b).reshape(2,5)

array([[20, 30, 40, 50, 60],
       [22, 32, 42, 52, 62]])

In [ ]:
np.append(a,b).reshape(10,1)

array([[20],
       [30],
       [40],
       [50],
       [60],
       [22],
       [32],
       [42],
       [52],
       [62]])

**insert()**

insert is also similar to append.

insert is taken single dimension continuous memory location index array.

In [ ]:
a=np.array([[2,3,4,5,6,7,8],[22,33,44,55,66,77,88]])
print(a)

[[ 2  3  4  5  6  7  8]
 [22 33 44 55 66 77 88]]


In [ ]:
np.insert(a,2,33)

array([ 2,  3, 33,  4,  5,  6,  7,  8, 22, 33, 44, 55, 66, 77, 88])

In [ ]:
np.insert(a,7,[2,3,33,4,5,6,7,8,22,33,44,55,66,77,88]).reshape(1,29,1)

array([[[ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 2],
        [ 3],
        [33],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [22],
        [33],
        [44],
        [55],
        [66],
        [77],
        [88],
        [22],
        [33],
        [44],
        [55],
        [66],
        [77],
        [88]]])

**delete()**

In [ ]:
a=np.array([2,3,4,5,6,7,8])
print(a)

[2 3 4 5 6 7 8]


In [ ]:
np.delete(a,2)

array([2, 3, 5, 6, 7, 8])

In [ ]:
np.delete(a,0)

array([3, 4, 5, 6, 7, 8])

**concatenate()**

two different arrays are concatenated

In [ ]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
b=np.array([11,12,13,14,15,16,17])
b

array([11, 12, 13, 14, 15, 16, 17])

In [ ]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
np.concatenate((a,b),axis=0)

array([ 1,  2,  3,  4,  5,  6,  7, 11, 12, 13, 14, 15, 16, 17])

stack()

vstack()

hstack()

dstack()

these all are used for joining arrays

In [ ]:
a=np.array([234,235,236,237,238,239])
a

array([234, 235, 236, 237, 238, 239])

In [ ]:
b=np.array([22,33,44,55,66,77])
b

array([22, 33, 44, 55, 66, 77])

In [ ]:
np.stack((a,b))

array([[234, 235, 236, 237, 238, 239],
       [ 22,  33,  44,  55,  66,  77]])

In [ ]:
res=np.stack((a,b))

In [ ]:
res

array([[234, 235, 236, 237, 238, 239],
       [ 22,  33,  44,  55,  66,  77]])

In [ ]:
res[1]

array([22, 33, 44, 55, 66, 77])

**vstack()**

In [ ]:
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [ ]:
b=np.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [ ]:
np.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

**hstack()**

horizontal stack

In [ ]:
a=np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [ ]:
b=np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

**depth wise()**

dstack()

In [ ]:
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [ ]:
b=np.array([[50,60],[70,80]])
b

array([[50, 60],
       [70, 80]])

In [ ]:
np.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

**split()**

In [ ]:
x=np.arange(5,60,2)
print(x)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59]


In [ ]:
np.split(x,7)

[array([ 5,  7,  9, 11]),
 array([13, 15, 17, 19]),
 array([21, 23, 25, 27]),
 array([29, 31, 33, 35]),
 array([37, 39, 41, 43]),
 array([45, 47, 49, 51]),
 array([53, 55, 57, 59])]

In [ ]:
np.split(x,14)

[array([5, 7]),
 array([ 9, 11]),
 array([13, 15]),
 array([17, 19]),
 array([21, 23]),
 array([25, 27]),
 array([29, 31]),
 array([33, 35]),
 array([37, 39]),
 array([41, 43]),
 array([45, 47]),
 array([49, 51]),
 array([53, 55]),
 array([57, 59])]

In [ ]:
s1,s2,s3,s4,s5,s6,s7=np.split(x,7)

In [ ]:
s1

array([ 5,  7,  9, 11])

In [ ]:
s2

array([13, 15, 17, 19])

In [ ]:
s3

array([21, 23, 25, 27])

In [ ]:
s4

array([29, 31, 33, 35])

In [ ]:
s5

array([37, 39, 41, 43])

In [ ]:
s6

array([45, 47, 49, 51])

In [ ]:
s7

array([53, 55, 57, 59])

**where()**

it checks whether the elements are present in the array or not

In [ ]:
a

array([[10, 20],
       [30, 40]])

In [ ]:
a=np.arange(5,65,5).reshape(4,3)
a

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [ ]:
np.where(a==55)

(array([3]), array([1]))

In [ ]:
a=np.arange(5,65,5).reshape(6,2)
a

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50],
       [55, 60]])

In [ ]:
np.where(a==40)

(array([3]), array([1]))

In [ ]:
np.where(a==45)

(array([4]), array([0]))

In [ ]:
np.where(a==46)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
np.where(a==47)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
np.where(a==56)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
np.where(a==36)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
np.where(a==26)

(array([], dtype=int64), array([], dtype=int64))

**searchsorted()**

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.searchsorted(a,5)

4

                                                **ARITHMETIC OPERATIONS**                                                                

add()

subtract()

multiply()

divide()

exp()

sqrt()

comparision()

addition

In [ ]:
a=np.array([[23,35,46],[65,74,87]])
a

array([[23, 35, 46],
       [65, 74, 87]])

In [ ]:
b=np.array([[36,12,33],[98,44,56]])
b

array([[36, 12, 33],
       [98, 44, 56]])

In [ ]:
np.add(a,b)

array([[ 59,  47,  79],
       [163, 118, 143]])

subtract

In [ ]:
np.subtract(a,b)

array([[-13,  23,  13],
       [-33,  30,  31]])

multiply

In [ ]:
np.multiply(a,b)

array([[ 828,  420, 1518],
       [6370, 3256, 4872]])

divide

In [ ]:
np.divide(a,b)

array([[0.63888889, 2.91666667, 1.39393939],
       [0.66326531, 1.68181818, 1.55357143]])

exponential

In [ ]:
np.exp(a)

array([[9.74480345e+09, 1.58601345e+15, 9.49611942e+19],
       [1.69488924e+28, 1.37338298e+32, 6.07603023e+37]])

square root

In [ ]:
np.sqrt(b)

array([[6.        , 3.46410162, 5.74456265],
       [9.89949494, 6.63324958, 7.48331477]])

comparision

In [ ]:
a

array([[23, 35, 46],
       [65, 74, 87]])

In [ ]:
b

array([[36, 12, 33],
       [98, 44, 56]])

In [ ]:
np.array_equal(a,b)

False

                                     **ARRAY FUNCTIONS**

sum()

min()

max()

mean()

median()

var()

std()

min()

In [ ]:
a=np.array([[100,200],[300,400],[500,600]])
a

array([[100, 200],
       [300, 400],
       [500, 600]])

In [ ]:
np.min(a)

100

In [ ]:
np.max(a)

600

In [ ]:
np.sum(a)

2100

In [ ]:
np.mean(a)

350.0

In [ ]:
np.median(a)

350.0

In [ ]:
np.var(a)

29166.666666666668

In [ ]:
np.std(a)

170.78251276599332